[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
evm-version = "cancun"
is-system= true
via-ir = true
optimizer = true
optimizer_runs = 100
solc_version = "0.8.26"
remappings = [
    "@arbitrum/=node_modules/@arbitrum/",
    "@chainlink/=node_modules/@chainlink/",
    "@eth-optimism/=node_modules/@eth-optimism/",
    "@layerzerolabs/=node_modules/@layerzerolabs/",
    "@offchainlabs/=node_modules/@offchainlabs/",
    "@openzeppelin-3/=node_modules/@openzeppelin-3/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@scroll-tech/=node_modules/@scroll-tech/",
     "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@uniswap/=node_modules/@uniswap/",
    "erc721a/=node_modules/erc721a/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "hardhat/=node_modules/hardhat/",
]


[profile.deploy]
rpc_url = "https://sepolia.base.org"

[profile.mainnet]
private_key = "YOUR_PRIVATE_KEY"
rpc_url = "https://sepolia.infura.io/v3/YOUR_INFURA_PROJECT_ID"
